# Generated by Django 5.0.2 on 2024-03-19 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_user_artist_type_artist_type_show_representation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representation_user',
            name='places',
        ),
    ]
